Changed to Styled Components and changed formating to fit new rules
gradeab/customer_status_internal_view pull request #4
Opened 2022-03-18 13:10 UTC by oskarjonszon

2022-03-23 10:54 UTC, arpi09 requested changes
Snyggt! Några småsaker att kolla på

2022-03-23 10:54 UTC, arpi09 commented on CustomerStatus/application/src/components/Contract.tsx
> +  let contract = useFetch<ContractDB>(`/api/contract/${id}`);
Ändra till const

2022-03-23 10:54 UTC, arpi09 commented on CustomerStatus/application/src/components/Contracts.tsx
> +                  {formatDate(contract.startDate || "")}{" "}
Ta bort alla {" "}

2022-03-23 10:54 UTC, arpi09 commented on CustomerStatus/application/src/components/Customer.tsx
> +  let customer = useFetch<CustomerDB>(`/api/customer/${id}`);
Ändra till const där möjligt

2022-03-23 10:54 UTC, arpi09 commented on CustomerStatus/application/src/components/Customers.tsx
> +                  {" "}
Ta bort alla {" "}

2022-03-23 10:54 UTC, arpi09 commented on CustomerStatus/application/src/components/Modules.tsx
> +  //const { data, isLoading, error } = useFetch();
Ta bort om inte används

2022-03-24 07:47 UTC, arpi09 requested changes
Hittade någon sak till

2022-03-24 07:47 UTC, arpi09 commented on CustomerStatus/application/src/components/Contracts.tsx
> +          <h1> Loading... </h1>
Ändra till loader komponent

2022-03-24 07:47 UTC, arpi09 commented on CustomerStatus/application/src/hooks/useFetch.tsx
> +    let signal = controller.signal;
Ändra till const

2022-03-24 07:47 UTC, arpi09 commented on CustomerStatus/application/src/hooks/useListStorage.tsx
> +      localStorage.setItem(key, JSON.stringify(value));
Vad används den här till?

2022-03-24 20:33 UTC, oskarjonszon commented on CustomerStatus/application/src/hooks/useListStorage.tsx
> +      localStorage.setItem(key, JSON.stringify(value));
Använder den för att spara en lista med favoriter i localstorage. :)
T.ex: `favorites : [0, 1, 2]`.

2022-03-24 20:37 UTC, oskarjonszon commented on CustomerStatus/application/src/components/Contracts.tsx
> +          <h1> Loading... </h1>
Tror redan dessa har blivit ändrade i en tidigare PR.

2022-03-25 05:42 UTC, arpi09 approved these changes
Bra jobbat!

2022-03-25 11:04 UTC, merged